Tt 29 groups view
kBlazewicz/group-enroll pull request #30
Opened 2023-05-23 22:24 UTC by ossimon

Stworzyłem wyświetlanie wygenerowanych grup.

Potrzebowałem niestety domerge'ować brancha z endpointem generowania grup na backendzie, przez co wygląda to tak, jakbym wprowadził także tamte zmiany. Można się wstrzymać z merge'owaniem do maina, dopóki tamten branch nie zostanie zmerge'owany, ale chciałem, żeby dało się zrobić code review.

2023-05-24 20:13 UTC, Paulina100 requested changes
Masz parę uwag. 
I może domerguj to po tym jak Karol domerguje swoje.

2023-05-24 20:13 UTC, Paulina100 commented on client/src/api/api-utils.ts
> +export const fetchStudents = async (): Promise<Student[]> => {
Można by posortować listę studentów np. alfabetycznie.
I wycentrować diva

2023-05-24 20:13 UTC, Paulina100 commented on client/src/api/api-utils.ts
> +export const fetchVotes = async (): Promise<Vote[]> => {
Wycentrować diva

2023-05-24 20:13 UTC, Paulina100 commented on client/src/components/results-view/GroupsExport.tsx
> +    const csvData: string[][] = [[...groups.map(group => group.term.dayOfWeek + " " + group.term.startTime + " - " + group.term.endTime)]];
Zmień nazwę csv na coś w stylu Groups.csv

2023-05-24 20:13 UTC, Paulina100 commented on client/src/components/results-view/GroupsExport.tsx
> +    const csvData: string[][] = [[...groups.map(group => group.term.dayOfWeek + " " + group.term.startTime + " - " + group.term.endTime)]];
Zastanawia mnie jeszcze czy w tym csv nie powinno być więcej informacji o studentach. Bo po coś my je zbieramy.

2023-05-24 20:13 UTC, Paulina100 commented on client/src/components/results-view/VotesSummary.tsx
> +                                            {votes.some(vote => vote.termId === term.id && vote.studentId === student.id && vote.possibility) ? "Tak" : "Nie"}
Tak i Nie strasznie gryzą w oczy jak nie są wycentrowane

2023-05-24 20:13 UTC, Paulina100 commented on client/src/components/results-view/GroupsList.tsx
> +                            <li key={group.term.id} style={{ margin: 5, padding: 5, paddingTop: 0, backgroundColor: "#d45bafa0", borderRadius: 3}}>
Jakby się dało to wycentrować te grupy.

2023-05-27 13:48 UTC, mklimek001 commented on client/src/components/results-view/GroupsList.tsx
> +                                    <Typography variant="h6" sx={{ color: 'grey' }}>{group.term.startTime} {group.term.endTime}</Typography>
Typography powinno chyba służyć tylko do nagłówka, a terminy z mniejszym nagłówkiem lepiej dać w jakimś innym divie.

2023-05-27 13:48 UTC, mklimek001 commented on client/src/components/results-view/VotesSummary.tsx
> +                                    <Typography variant="h6" sx={{ color: 'grey' }}>{term.startTime} {term.endTime}</Typography>
Typography podobnie jak wyżej

2023-05-27 13:48 UTC, mklimek001 commented on client/src/components/results-view/GroupsList.tsx
> +                    {groups.map(group => {
Po kliknięciu wyrzuca
![eror_map](https://github.com/kBlazewicz/group-enroll/assets/74615934/f102e263-0fff-48b2-94e8-917ed4f0b582)
Może dlatego, że formularz studenta nie pozwala póki co wprowadzić więcej niż jednego studenta, ale i tak pasowałoby to jakoś zablokować. (np. alert jeśli studentów jest za mało)

2023-05-29 17:08 UTC, mklimek001 approved these changes

2023-05-29 17:14 UTC, Paulina100 approved these changes
Merguj

2023-05-29 17:15 UTC, merged